# =============================================
# MySQL
# =============================================
spring.datasource.url=jdbc:mysql://localhost:3306/user_management_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================================
# JPA
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

## =============================================
## FLYWAY - CONFIGURATION FINALE
## =============================================
#spring.flyway.enabled=true
#spring.flyway.baseline-on-migrate=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.sql-migration-prefix=V
#spring.flyway.validate-on-migrate=true
#spring.flyway.repair-on-migrate=false

# =============================================
# LOGS
# =============================================
#logging.level.org.flywaydb=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

# ============================================================
# LOGS SQL POUR DÉTECTER N+1
# ============================================================

# Afficher les valeurs des paramètres
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Afficher les statistiques Hibernate
spring.jpa.properties.hibernate.generate_statistics=true

# Formater les requêtes pour les lire

app.jwt.secret==VGhpc0lzQVN1ZmZpY2llbnRseUxvbmdTZWNyZXRLZXlGb3JUZXN0aW5nMjAyNg=
app.jwt.expiration-ms=864000000

# Activer les logs de cache
logging.level.org.springframework.cache=DEBUG
logging.level.com.github.benmanes.caffeine=DEBUG
logging.level.org.springframework.aop=DEBUG


# ============================================================
# REDIS CONFIGURATION
# ============================================================

# Adresse du serveur Redis
spring.redis.host=localhost

# Port de Redis (par défaut: 6379)
spring.redis.port=6379

# Timeout de connexion (2 secondes)
spring.redis.timeout=2000ms

# Configuration du pool de connexions
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0


# ============================================================
# SPRING ACTUATOR - MONITORING
# ============================================================

# Exposer tous les endpoints Actuator
management.endpoints.web.exposure.include=*

# Afficher les détails de santé
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always

# Activer toutes les métriques
management.metrics.enable.all=true

# Activer les informations de build
management.info.build.enabled=true
management.info.env.enabled=true
management.info.java.enabled=true

# Activer les probes pour Kubernetes (optionnel mais utile)
management.health.probes.enabled=true

# Permettre de changer les logs en runtime
management.endpoint.loggers.enabled=true

# Exposer Prometheus
management.endpoint.prometheus.enabled=true



