server.port=${PORT:8080}

spring.datasource.url=${JDBC_DATABASE_URL}
spring.datasource.username=${JDBC_DATABASE_USERNAME}
spring.datasource.password=${JDBC_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.generate_statistics=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=864000000

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.metrics.enable.all=true
management.info.build.enabled=true
management.info.env.enabled=true
management.info.java.enabled=true
management.health.probes.enabled=true
management.endpoint.prometheus.enabled=true

logging.level.com.formation.usermanagement=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN

spring.redis.host=localhost
spring.redis.port=6379
spring.redis.timeout=2000ms